#pragma once
/**
 * Chain params constants for each tracked chain.
 * @generated by contrib/devtools/chainparams/generate_chainparams_constants.py
 */

#include <primitives/blockhash.h>
#include <uint256.h>

namespace ChainParamsConstants {
    // NOTE: the two MAINNET_* values below were MANUALLY updated for v3.1.2 to
    // anchor the canonical chain at block 438,204 (the first block above the
    // 2026-06-15 fork base 438,203). If contrib/devtools/chainparams/
    // generate_chainparams_constants.py is ever re-run, it MUST regenerate from
    // the canonical (most-work) chain, not the abandoned minority fork, so these
    // are not reverted. assume-valid = block 438,204; minimum-chain-work = its
    // chainwork (verified against the live canonical node).
    const BlockHash MAINNET_DEFAULT_ASSUME_VALID = BlockHash::fromHex("00000000000000660f27b62d38e4e55d74fb253f5845697b268233ccbe78529d");
    const uint256 MAINNET_MINIMUM_CHAIN_WORK = uint256S("00000000000000000000000000000000000000000000156307d805c8602f7b39");

    const BlockHash TESTNET_DEFAULT_ASSUME_VALID = BlockHash::fromHex("00000000fb574b8ace948acaa62a60ef24ee504b9f8fbf430ac77f514ea1f6fc");
    const uint256 TESTNET_MINIMUM_CHAIN_WORK = uint256S("00000000000000000000000000000000000000000000000000000e200e200e20");

    // Scalenet re-organizes above height 10,000 - use block 9,999 hash here.
    const BlockHash SCALENET_DEFAULT_ASSUME_VALID = BlockHash::fromHex("0000000090d0f97e1825d5e8c47ad32110abad0f7340f73e5b3d92baf55b2a76");
    const uint256 SCALENET_MINIMUM_CHAIN_WORK = uint256S("00000000000000000000000000000000000000000000000000000e200e200e20");
} // namespace ChainParamsConstants
