# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BUILD_SOURCE_DIRS "/Users/main/Downloads/Radiant-Core-main;/Users/main/Downloads/Radiant-Core-main/macos-arm64-release")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/opt/homebrew/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "radiant-core built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "TGZ")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/Users/main/Downloads/Radiant-Core-main/macos-arm64-release;radiant-core;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/Users/main/Downloads/Radiant-Core-main/cmake/modules")
set(CPACK_MONOLITHIC_INSTALL "ON")
set(CPACK_NSIS_COMPRESSOR "/SOLID lzma")
set(CPACK_NSIS_CONTACT "info@radiantblockchain.org")
set(CPACK_NSIS_CREATE_ICONS_EXTRA "CreateShortCut '$SMPROGRAMS\\$STARTMENU_FOLDER\\Radiant Core (testnet).lnk' '$INSTDIR\\bin\\bitcoin-qt.exe' '-testnet' '$INSTDIR\\bin\\bitcoin-qt.exe' '1'")
set(CPACK_NSIS_DELETE_ICONS_EXTRA "Delete '$SMPROGRAMS\\$START_MENU\\Radiant Core (testnet).lnk'")
set(CPACK_NSIS_DISPLAY_NAME "Radiant Core")
set(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL "ON")
set(CPACK_NSIS_EXECUTABLES_DIRECTORY "bin")
set(CPACK_NSIS_INSTALLED_ICON_NAME "bin/bitcoin-qt.exe")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_MENU_LINKS "bin/bitcoin-qt.exe;Radiant Node")
set(CPACK_NSIS_MUI_FINISHPAGE_RUN "bitcoin-qt.exe")
set(CPACK_NSIS_MUI_ICON "/Users/main/Downloads/Radiant-Core-main/share/pixmaps/bitcoin.ico")
set(CPACK_NSIS_MUI_UNIICON "/Users/main/Downloads/Radiant-Core-main/share/pixmaps/bitcoin.ico")
set(CPACK_NSIS_MUI_UNWELCOMEFINISHPAGE_BITMAP "/Users/main/Downloads/Radiant-Core-main/share/pixmaps/nsis-wizard.bmp")
set(CPACK_NSIS_MUI_WELCOMEFINISHPAGE_BITMAP "/Users/main/Downloads/Radiant-Core-main/share/pixmaps/nsis-wizard.bmp")
set(CPACK_NSIS_PACKAGE_NAME "Radiant Core")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_NSIS_URL_INFO_ABOUT "https://radiantblockchain.org")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/Users/main/Downloads/Radiant-Core-main/macos-arm64-release/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "info@radiantblockchain.org")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "Radiant Node is a Radiant full node implementation.")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/Users/main/Downloads/Radiant-Core-main/doc/README_windows.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Radiant Core is a full node implementation of the Radiant Blockchain protocol, RXD.")
set(CPACK_PACKAGE_FILE_NAME "radiant-core-2.3.0-Darwin")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://radiantblockchain.org")
set(CPACK_PACKAGE_ICON "/Users/main/Downloads/Radiant-Core-main/share/pixmaps/bitcoin128.png")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "radiant-node")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "radiant-node")
set(CPACK_PACKAGE_NAME "radiant-core")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "")
set(CPACK_PACKAGE_VERSION "2.3.0")
set(CPACK_PACKAGE_VERSION_MAJOR "2")
set(CPACK_PACKAGE_VERSION_MINOR "3")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "/Users/main/Downloads/Radiant-Core-main/COPYING")
set(CPACK_RESOURCE_FILE_README "/opt/homebrew/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/opt/homebrew/share/cmake/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_IGNORE_FILES "/Users/main/Downloads/Radiant-Core-main/.DS_Store$;/Users/main/Downloads/Radiant-Core-main/.pytest_cache/;/Users/main/Downloads/Radiant-Core-main/.vscode/;/Users/main/Downloads/Radiant-Core-main/build-qt/;/Users/main/Downloads/Radiant-Core-main/build-v2.1.2/;/Users/main/Downloads/Radiant-Core-main/build/;/Users/main/Downloads/Radiant-Core-main/depends/sources/;/Users/main/Downloads/Radiant-Core-main/doc/release-notes/release-notes-2.0.1.md$;/Users/main/Downloads/Radiant-Core-main/doc/release-notes/release-notes-2.1.1.md$;/Users/main/Downloads/Radiant-Core-main/doc/release-notes/release-notes-2.1.2.md$;/Users/main/Downloads/Radiant-Core-main/doc/release-notes/release-notes-2.2.0.md$;/Users/main/Downloads/Radiant-Core-main/doc/release-notes/release-notes-2.3.0.md$;/Users/main/Downloads/Radiant-Core-main/gui/__pycache__/;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_charconv.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_context.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_contract.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_coroutine.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_fiber.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_filesystem.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_graph.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_iostreams.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_json.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_locale.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_log.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_log_setup.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_math_c99.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_math_c99f.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_math_c99l.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_math_tr1.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_math_tr1f.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_math_tr1l.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_nowide.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_prg_exec_monitor.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_process.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_program_options.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_random.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_regex.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_serialization.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_stacktrace_addr2line.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_stacktrace_basic.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_stacktrace_noop.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_timer.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_type_erasure.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_unit_test_framework.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_url.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_wave.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libboost_wserialization.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libdb_cxx-4.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libdb_cxx.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libevent.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libevent_core-2.1.7.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libevent_core.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libevent_extra-2.1.7.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libevent_extra.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libevent_openssl-2.1.7.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libevent_openssl.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libevent_pthreads.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libminiupnpc.21.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libminiupnpc.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/binaries/radiant-core-macos-arm64/libs/libzmq.dylib$;/Users/main/Downloads/Radiant-Core-main/gui/build/;/Users/main/Downloads/Radiant-Core-main/gui/dist/;/Users/main/Downloads/Radiant-Core-main/gui/venv/;/Users/main/Downloads/Radiant-Core-main/macos-app-build/Radiant-Core-GUI-2.1.2.dmg$;/Users/main/Downloads/Radiant-Core-main/macos-app-build/Radiant-Core-GUI-2.1.2.dmg.sha256$;/Users/main/Downloads/Radiant-Core-main/macos-app-build/bip39.py$;/Users/main/Downloads/Radiant-Core-main/macos-app-build/build.log$;/Users/main/Downloads/Radiant-Core-main/macos-app-build/dist/;/Users/main/Downloads/Radiant-Core-main/macos-app-build/doc/;/Users/main/Downloads/Radiant-Core-main/macos-app-build/radiant_node_web.py$;/Users/main/Downloads/Radiant-Core-main/macos-release/;/Users/main/Downloads/Radiant-Core-main/network_monitor.py$;/Users/main/Downloads/Radiant-Core-main/releases/.DS_Store$;/Users/main/Downloads/Radiant-Core-main/releases/v2.0.0/.DS_Store$;/Users/main/Downloads/Radiant-Core-main/releases/v2.0.1/.DS_Store$;/Users/main/Downloads/Radiant-Core-main/releases/v2.1.0/.DS_Store$;/Users/main/Downloads/Radiant-Core-main/releases/v2.1.1/.DS_Store$;/Users/main/Downloads/Radiant-Core-main/releases/v2.1.2/.DS_Store$;/Users/main/Downloads/Radiant-Core-main/releases/v2.1.2/Radiant-Core-Qt-Wallet-2.1.2.dmg$;/Users/main/Downloads/Radiant-Core-main/releases/v2.1.2/RadiantCore-Qt.app/;/Users/main/Downloads/Radiant-Core-main/releases/v2.2.0/.DS_Store$;/Users/main/Downloads/Radiant-Core-main/releases/v2.2.0/Radiant-Core-Qt-Wallet-2.2.0.dmg$;/Users/main/Downloads/Radiant-Core-main/releases/v2.2.0/RadiantCore-Qt.app/;/Users/main/Downloads/Radiant-Core-main/test/cache/;/Users/main/Downloads/Radiant-Core-main/test/functional/test_framework/__pycache__/;/\\.;/Users/main/Downloads/Radiant-Core-main/macos-arm64-release/;/Users/main/Downloads/Radiant-Core-main/depends/;/Users/main/Downloads/Radiant-Core-main/[^.]+[.]md$;/Users/main/Downloads/Radiant-Core-main/test/cache/;/Users/main/Downloads/Radiant-Core-main/test/lint/;/Users/main/Downloads/Radiant-Core-main/test/sanitizer_suppressions/;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/bitcoind-exit-on-log.sh;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/circular-dependencies.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/copyright_header.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/extract_strings_qt.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/gitian-build.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/optimize-pngs.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/README.md;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/test-security-check.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/update-translations.py;/Users/main/Downloads/Radiant-Core-main/contrib/debian/;/Users/main/Downloads/Radiant-Core-main/contrib/gitian/;/Users/main/Downloads/Radiant-Core-main/contrib/gitian-descriptors/;/Users/main/Downloads/Radiant-Core-main/contrib/qos/;/Users/main/Downloads/Radiant-Core-main/contrib/seeds/;/Users/main/Downloads/Radiant-Core-main/contrib/testgen/;/Users/main/Downloads/Radiant-Core-main/contrib/zmq/;/Users/main/Downloads/Radiant-Core-main/contrib/bitcoin-qt.pro;/Users/main/Downloads/Radiant-Core-main/contrib/gitian-build.py;/Users/main/Downloads/Radiant-Core-main/contrib/README.md;/Users/main/Downloads/Radiant-Core-main/contrib/valgrind.supp")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/main/Downloads/Radiant-Core-main/macos-arm64-release/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "radiant-core-2.3.0")
set(CPACK_SYSTEM_NAME "Darwin")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Darwin")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/main/Downloads/Radiant-Core-main/macos-arm64-release/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
